### ISSUE TITLE
Basic documentation

### ISSUE THREAD

**Issue by WichardRiezebos** [WichardRiezebos/astar-navigator#2]
Add basic documentation to the public members.

**Comment by peon501** [comment]
how to block tiles ?

**Comment by WichardRiezebos** [comment]
You can implement an interface to block specific tiles, the [EmptyBlockedProvider](https://github.com/WichardRiezebos/astar-navigator/blob/master/AStarNavigator/Providers/EmptyBlockedProvider.cs) is an example.
